/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.WorkAreas;

import Business.DataGenerator;
import Business.Employee.Employee;
import Business.Enterprise.DigitalEntertainment;
import Business.Enterprise.Enterprise;
import Business.Enterprise.EnterpriseType;
import Business.Enterprise.HardwareAndSupplyChain;
import Business.Enterprise.PartnerAndService;
import Business.Organization.Organization;
import Business.Organization.OrganizationType;
import Business.Role.Role;
import Business.Role.RoleType;
import Business.SonyEcoSystem;
import Business.UserAccount.UserAccount;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sumayyahhusain
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {

    private final SonyEcoSystem ecosystem;
    private final ArrayList<UserAccount> displayedUsers;
    private final ArrayList<Organization> displayedOrganizations;
    private final ArrayList<Enterprise> displayedEnterprises;

    private UserAccount selectedUserAccount;
    private Organization selectedOrganization;
    private Enterprise selectedEnterprise;
    
    /**
     * Creates new form AdminWorkAreaJPanel
     */
    
    public AdminWorkAreaJPanel() {
        this(DataGenerator.createSeededEcosystem());
    }
    
    public AdminWorkAreaJPanel(SonyEcoSystem ecosystem) {
        this.ecosystem = ecosystem == null ? DataGenerator.createSeededEcosystem() : ecosystem;
        this.displayedUsers = new ArrayList<>();
        this.displayedOrganizations = new ArrayList<>();
        this.displayedEnterprises = new ArrayList<>();
        initComponents();
        initializeAdminWorkspace();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTab = new javax.swing.JTabbedPane();
        UserTab = new javax.swing.JTabbedPane();
        jSplitPane2 = new javax.swing.JSplitPane();
        RightPanel = new javax.swing.JPanel();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        lblOrganization = new javax.swing.JLabel();
        lblEnterprise = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        cmbRole = new javax.swing.JComboBox<>();
        cmbOragnization = new javax.swing.JComboBox<>();
        cmbEnterprise = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        LeftPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUser = new javax.swing.JTable();
        lblSearch = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        OrgTab = new javax.swing.JTabbedPane();
        jSplitPane1 = new javax.swing.JSplitPane();
        OrgLeftPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrganization = new javax.swing.JTable();
        btnSearchOrg = new javax.swing.JButton();
        btnAddOrg = new javax.swing.JButton();
        lblSearchOrg = new javax.swing.JLabel();
        txtSearchOrg = new javax.swing.JTextField();
        btnDeleteOrg = new javax.swing.JButton();
        OrgRightPanel = new javax.swing.JPanel();
        lblOrgName = new javax.swing.JLabel();
        lblEnterpriseOrg = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtEnterpriseOrg = new javax.swing.JTextField();
        btnClearOrg = new javax.swing.JButton();
        cmbStatus = new javax.swing.JComboBox<>();
        btnUpdateOrg = new javax.swing.JButton();
        EnterpriseTab = new javax.swing.JTabbedPane();
        jSplitPane3 = new javax.swing.JSplitPane();
        EnterLeftPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblEnterprise = new javax.swing.JTable();
        lblEnterSearch = new javax.swing.JLabel();
        txtEnterSearch = new javax.swing.JTextField();
        btnEnterSearch = new javax.swing.JButton();
        btnEnterDelete = new javax.swing.JButton();
        btnAddOrg1 = new javax.swing.JButton();
        EnterRightPanel = new javax.swing.JPanel();
        lblEnterName = new javax.swing.JLabel();
        lblEnterType = new javax.swing.JLabel();
        lblEnterStatus = new javax.swing.JLabel();
        txtEnterName = new javax.swing.JTextField();
        txtEnterType = new javax.swing.JTextField();
        cmbEnterStatus = new javax.swing.JComboBox<>();
        btnEnterClear = new javax.swing.JButton();
        btnEnterUpdate = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        mainTab.setBackground(new java.awt.Color(204, 204, 204));
        mainTab.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        UserTab.setBackground(new java.awt.Color(204, 204, 204));
        UserTab.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        UserTab.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N

        jSplitPane2.setDividerLocation(550);

        RightPanel.setBackground(new java.awt.Color(255, 255, 255));
        RightPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "User Details"));

        lblFirstName.setText("First Name:");

        lblLastName.setText("Last Name:");

        lblEmail.setText("Email:");

        lblPhone.setText("Phone");

        lblUsername.setText("Username:");

        lblPassword.setText("Password:");

        lblRole.setText("Role:");

        lblOrganization.setText("Organization: ");

        lblEnterprise.setText("Status:");

        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbOragnization.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbEnterprise.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnSave.setBackground(new java.awt.Color(204, 204, 204));
        btnSave.setText("Save");
        btnSave.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(204, 204, 204));
        btnClear.setText("Clear");
        btnClear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout RightPanelLayout = new javax.swing.GroupLayout(RightPanel);
        RightPanel.setLayout(RightPanelLayout);
        RightPanelLayout.setHorizontalGroup(
            RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblOrganization, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblRole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblEnterprise, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblFirstName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(txtLastName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPhone, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsername, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbRole, javax.swing.GroupLayout.Alignment.LEADING, 0, 136, Short.MAX_VALUE)
                    .addComponent(cmbOragnization, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbEnterprise, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
            .addGroup(RightPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        RightPanelLayout.setVerticalGroup(
            RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastName)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhone)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRole)
                    .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrganization)
                    .addComponent(cmbOragnization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnterprise)
                    .addComponent(cmbEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnClear))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane2.setRightComponent(RightPanel);

        LeftPanel.setBackground(new java.awt.Color(255, 255, 255));
        LeftPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("")));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "User ID", "Full Name", "Email", "Role", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblUser);

        lblSearch.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        lblSearch.setText("Search:");

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(204, 204, 204));
        btnSearch.setText("Search");
        btnSearch.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(204, 204, 204));
        btnEdit.setText("Edit");
        btnEdit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(204, 204, 204));
        btnDelete.setText("Delete");
        btnDelete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LeftPanelLayout = new javax.swing.GroupLayout(LeftPanel);
        LeftPanel.setLayout(LeftPanelLayout);
        LeftPanelLayout.setHorizontalGroup(
            LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftPanelLayout.createSequentialGroup()
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LeftPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LeftPanelLayout.createSequentialGroup()
                                .addComponent(lblSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 162, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE))))
                .addContainerGap())
        );
        LeftPanelLayout.setVerticalGroup(
            LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearch)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete))
                .addGap(45, 45, 45))
        );

        jSplitPane2.setLeftComponent(LeftPanel);

        UserTab.addTab("User lists", jSplitPane2);

        mainTab.addTab("User", UserTab);

        OrgTab.setBackground(new java.awt.Color(204, 204, 204));
        OrgTab.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        OrgTab.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N

        OrgLeftPanel.setBackground(new java.awt.Color(255, 255, 255));
        OrgLeftPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        OrgLeftPanel.setPreferredSize(new java.awt.Dimension(550, 450));

        tblOrganization.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblOrganization.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Oragnization ID", "Organization Name", "Status", "Last Updated"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblOrganization);

        btnSearchOrg.setBackground(new java.awt.Color(204, 204, 204));
        btnSearchOrg.setText("Search");
        btnSearchOrg.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnAddOrg.setBackground(new java.awt.Color(204, 204, 204));
        btnAddOrg.setText("Add");
        btnAddOrg.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAddOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOrgActionPerformed(evt);
            }
        });

        lblSearchOrg.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        lblSearchOrg.setText("Search:");

        btnDeleteOrg.setBackground(new java.awt.Color(204, 204, 204));
        btnDeleteOrg.setText("Delete");
        btnDeleteOrg.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout OrgLeftPanelLayout = new javax.swing.GroupLayout(OrgLeftPanel);
        OrgLeftPanel.setLayout(OrgLeftPanelLayout);
        OrgLeftPanelLayout.setHorizontalGroup(
            OrgLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrgLeftPanelLayout.createSequentialGroup()
                .addGroup(OrgLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OrgLeftPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(OrgLeftPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lblSearchOrg)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearchOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(OrgLeftPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        OrgLeftPanelLayout.setVerticalGroup(
            OrgLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrgLeftPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(OrgLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearchOrg)
                    .addComponent(txtSearchOrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchOrg))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(OrgLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDeleteOrg)
                    .addComponent(btnAddOrg))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(OrgLeftPanel);

        OrgRightPanel.setBackground(new java.awt.Color(255, 255, 255));
        OrgRightPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Oragnization Details"));

        lblOrgName.setText("Name:");

        lblEnterpriseOrg.setText("Enterprise:");

        lblStatus.setText("Status:");

        btnClearOrg.setBackground(new java.awt.Color(204, 204, 204));
        btnClearOrg.setText("Clear");
        btnClearOrg.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Active", "Deactive", " " }));

        btnUpdateOrg.setBackground(new java.awt.Color(204, 204, 204));
        btnUpdateOrg.setText("Update");
        btnUpdateOrg.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUpdateOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateOrgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OrgRightPanelLayout = new javax.swing.GroupLayout(OrgRightPanel);
        OrgRightPanel.setLayout(OrgRightPanelLayout);
        OrgRightPanelLayout.setHorizontalGroup(
            OrgRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrgRightPanelLayout.createSequentialGroup()
                .addGroup(OrgRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OrgRightPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(OrgRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblOrgName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEnterpriseOrg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(OrgRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(txtEnterpriseOrg)
                            .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(OrgRightPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnUpdateOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnClearOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        OrgRightPanelLayout.setVerticalGroup(
            OrgRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrgRightPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(OrgRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrgName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(OrgRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnterpriseOrg)
                    .addComponent(txtEnterpriseOrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(OrgRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(OrgRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClearOrg)
                    .addComponent(btnUpdateOrg))
                .addContainerGap(240, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(OrgRightPanel);

        OrgTab.addTab("Organization Lists", jSplitPane1);

        mainTab.addTab("Organizations", OrgTab);

        EnterpriseTab.setBackground(new java.awt.Color(204, 204, 204));
        EnterpriseTab.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        EnterpriseTab.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N

        EnterLeftPanel.setBackground(new java.awt.Color(255, 255, 255));
        EnterLeftPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        EnterLeftPanel.setPreferredSize(new java.awt.Dimension(550, 450));

        jScrollPane3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblEnterprise.setBackground(new java.awt.Color(204, 204, 204));
        tblEnterprise.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblEnterprise.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Enterprise Name", "Enterprise Type", "Status", "Last Updated"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblEnterprise);

        lblEnterSearch.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        lblEnterSearch.setText("Search:");

        btnEnterSearch.setBackground(new java.awt.Color(204, 204, 204));
        btnEnterSearch.setText("Search");
        btnEnterSearch.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnEnterDelete.setBackground(new java.awt.Color(204, 204, 204));
        btnEnterDelete.setText("Delete");
        btnEnterDelete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnAddOrg1.setBackground(new java.awt.Color(204, 204, 204));
        btnAddOrg1.setText("Add");
        btnAddOrg1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAddOrg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOrg1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EnterLeftPanelLayout = new javax.swing.GroupLayout(EnterLeftPanel);
        EnterLeftPanel.setLayout(EnterLeftPanelLayout);
        EnterLeftPanelLayout.setHorizontalGroup(
            EnterLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnterLeftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EnterLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(EnterLeftPanelLayout.createSequentialGroup()
                        .addComponent(lblEnterSearch)
                        .addGap(18, 18, 18)
                        .addComponent(txtEnterSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEnterSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EnterLeftPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAddOrg1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEnterDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        EnterLeftPanelLayout.setVerticalGroup(
            EnterLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnterLeftPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(EnterLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnterSearch)
                    .addComponent(txtEnterSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnterSearch))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EnterLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnterDelete)
                    .addComponent(btnAddOrg1))
                .addContainerGap(173, Short.MAX_VALUE))
        );

        jSplitPane3.setLeftComponent(EnterLeftPanel);

        EnterRightPanel.setBackground(new java.awt.Color(255, 255, 255));
        EnterRightPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Enterprise Details"));
        EnterRightPanel.setPreferredSize(new java.awt.Dimension(300, 450));

        lblEnterName.setText("Enterprise Name:");

        lblEnterType.setText("Enterprise Type:");

        lblEnterStatus.setText("Status:");

        cmbEnterStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Active", "Deactive", " " }));

        btnEnterClear.setBackground(new java.awt.Color(204, 204, 204));
        btnEnterClear.setText("Clear");
        btnEnterClear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnEnterUpdate.setBackground(new java.awt.Color(204, 204, 204));
        btnEnterUpdate.setText("Update");
        btnEnterUpdate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEnterUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EnterRightPanelLayout = new javax.swing.GroupLayout(EnterRightPanel);
        EnterRightPanel.setLayout(EnterRightPanelLayout);
        EnterRightPanelLayout.setHorizontalGroup(
            EnterRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnterRightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EnterRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEnterName)
                    .addGroup(EnterRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblEnterStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblEnterType, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(EnterRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEnterName)
                    .addComponent(txtEnterType)
                    .addGroup(EnterRightPanelLayout.createSequentialGroup()
                        .addComponent(cmbEnterStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 152, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(EnterRightPanelLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(btnEnterUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEnterClear, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EnterRightPanelLayout.setVerticalGroup(
            EnterRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnterRightPanelLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(EnterRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnterName)
                    .addComponent(txtEnterName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(EnterRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnterType)
                    .addComponent(txtEnterType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(EnterRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnterStatus)
                    .addComponent(cmbEnterStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(EnterRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnterClear)
                    .addComponent(btnEnterUpdate))
                .addContainerGap(218, Short.MAX_VALUE))
        );

        jSplitPane3.setRightComponent(EnterRightPanel);

        EnterpriseTab.addTab("Enterprise Lists", jSplitPane3);

        mainTab.addTab("Enterprises", EnterpriseTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainTab, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(mainTab, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void initializeAdminWorkspace() {
        configurePanelTitles();
        configureComboBoxes();
        configureTables();
        registerEventHandlers();
        populateAllTables();
        clearUserForm();
        clearOrganizationForm();
        clearEnterpriseForm();
    }

    private void configurePanelTitles() {
        LeftPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "User List"));
        OrgLeftPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Organization List"));
        EnterLeftPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Enterprise List"));
        lblEnterprise.setText("Status:");
    }

    private void configureComboBoxes() {
        cmbEnterprise.setModel(new DefaultComboBoxModel<>(new String[]{"Active", "Inactive"}));
        cmbStatus.setModel(new DefaultComboBoxModel<>(new String[]{"Active", "Inactive"}));
        cmbEnterStatus.setModel(new DefaultComboBoxModel<>(new String[]{"Active", "Inactive"}));
        populateOrganizationCombo();
        populateRoleCombo(null);
    }

    private void configureTables() {
        tblUser.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblOrganization.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblEnterprise.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    private void registerEventHandlers() {
        btnSearch.addActionListener(evt -> populateUserTable(txtSearch.getText()));
        btnEdit.addActionListener(evt -> loadSelectedUser());
        btnDelete.addActionListener(evt -> deleteSelectedUser());
        btnSave.addActionListener(evt -> saveUser());
        btnClear.addActionListener(evt -> clearUserForm());

        btnSearchOrg.addActionListener(evt -> populateOrganizationTable(txtSearchOrg.getText()));
        btnAddOrg.addActionListener(evt -> {
            selectedOrganization = null;
            saveOrganization();
        });
        btnDeleteOrg.addActionListener(evt -> deleteSelectedOrganization());
        btnUpdateOrg.addActionListener(evt -> toggleSelectedOrganizationStatus());
        btnClearOrg.addActionListener(evt -> clearOrganizationForm());

        btnEnterSearch.addActionListener(evt -> populateEnterpriseTable(txtEnterSearch.getText()));
        btnEnterDelete.addActionListener(evt -> deleteSelectedEnterprise());
        btnEnterUpdate.addActionListener(evt -> toggleSelectedEnterpriseStatus());
        btnEnterClear.addActionListener(evt -> clearEnterpriseForm());

        cmbOragnization.addActionListener(evt -> populateRoleCombo(findOrganizationByName((String) cmbOragnization.getSelectedItem())));

        tblUser.getSelectionModel().addListSelectionListener(this::handleUserSelectionChanged);
        tblOrganization.getSelectionModel().addListSelectionListener(this::handleOrganizationSelectionChanged);
        tblEnterprise.getSelectionModel().addListSelectionListener(this::handleEnterpriseSelectionChanged);
    }

    private void handleUserSelectionChanged(ListSelectionEvent event) {
        if (!event.getValueIsAdjusting()) {
            int row = tblUser.getSelectedRow();
            if (row >= 0 && row < displayedUsers.size()) {
                selectedUserAccount = displayedUsers.get(row);
                loadUserIntoForm(selectedUserAccount);
            }
        }
    }

    private void handleOrganizationSelectionChanged(ListSelectionEvent event) {
        if (!event.getValueIsAdjusting()) {
            int row = tblOrganization.getSelectedRow();
            if (row >= 0 && row < displayedOrganizations.size()) {
                selectedOrganization = displayedOrganizations.get(row);
                loadOrganizationIntoForm(selectedOrganization);
            }
        }
    }

    private void handleEnterpriseSelectionChanged(ListSelectionEvent event) {
        if (!event.getValueIsAdjusting()) {
            int row = tblEnterprise.getSelectedRow();
            if (row >= 0 && row < displayedEnterprises.size()) {
                selectedEnterprise = displayedEnterprises.get(row);
                loadEnterpriseIntoForm(selectedEnterprise);
            }
        }
    }

    private void populateAllTables() {
        populateUserTable(null);
        populateOrganizationTable(null);
        populateEnterpriseTable(null);
    }

    private void populateUserTable(String searchText) {
        displayedUsers.clear();
        DefaultTableModel model = (DefaultTableModel) tblUser.getModel();
        model.setRowCount(0);

        String keyword = normalize(searchText);

        for (UserAccount account : ecosystem.getAllUserAccounts()) {
            Employee employee = account.getEmployee();
            String fullName = employee == null ? "" : employee.getName();
            String email = employee == null ? "" : employee.getEmail();
            String role = account.getRoleType() == null ? "" : account.getRoleType().getDisplayName();
            String status = account.isActive() ? "Active" : "Inactive";
            String searchable = normalize(account.getUsername() + " " + fullName + " " + email + " " + role + " " + status);

            if (!keyword.isEmpty() && !searchable.contains(keyword)) {
                continue;
            }

            displayedUsers.add(account);
            model.addRow(new Object[]{
                employee == null ? "-" : employee.getEmployeeId(),
                fullName,
                email,
                role,
                status
            });
        }
    }

    private void populateOrganizationTable(String searchText) {
        displayedOrganizations.clear();
        DefaultTableModel model = (DefaultTableModel) tblOrganization.getModel();
        model.setRowCount(0);

        String keyword = normalize(searchText);
        int rowIndex = 1;

        for (Organization organization : ecosystem.getOrganizationList()) {
            Enterprise enterprise = ecosystem.findEnterpriseByOrganization(organization);
            String searchable = normalize(
                    organization.getName() + " "
                    + organization.getType().getDisplayName() + " "
                    + (enterprise == null ? "" : enterprise.getName()) + " "
                    + (organization.isActive() ? "Active" : "Inactive")
            );

            if (!keyword.isEmpty() && !searchable.contains(keyword)) {
                continue;
            }

            displayedOrganizations.add(organization);
            model.addRow(new Object[]{
                String.format("ORG-%03d", rowIndex++),
                organization.getName(),
                organization.isActive() ? "Active" : "Inactive",
                LocalDate.now().toString()
            });
        }
    }

    private void populateEnterpriseTable(String searchText) {
        displayedEnterprises.clear();
        DefaultTableModel model = (DefaultTableModel) tblEnterprise.getModel();
        model.setRowCount(0);

        String keyword = normalize(searchText);

        for (Enterprise enterprise : ecosystem.getEnterpriseList()) {
            String searchable = normalize(
                    enterprise.getName() + " "
                    + enterprise.getType().getDisplayName() + " "
                    + (enterprise.isActive() ? "Active" : "Inactive")
            );

            if (!keyword.isEmpty() && !searchable.contains(keyword)) {
                continue;
            }

            displayedEnterprises.add(enterprise);
            model.addRow(new Object[]{
                enterprise.getName(),
                enterprise.getType().getDisplayName(),
                enterprise.isActive() ? "Active" : "Inactive",
                LocalDate.now().toString()
            });
        }
    }

    private void populateOrganizationCombo() {
        cmbOragnization.removeAllItems();
        for (Organization organization : ecosystem.getOrganizationList()) {
            cmbOragnization.addItem(organization.getName());
        }
    }

    private void populateRoleCombo(Organization organization) {
        cmbRole.removeAllItems();

        if (organization != null && !organization.getSupportedRoles().isEmpty()) {
            for (Role role : organization.getSupportedRoles()) {
                cmbRole.addItem(role.getType().getDisplayName());
            }
            return;
        }

        for (RoleType roleType : RoleType.values()) {
            cmbRole.addItem(roleType.getDisplayName());
        }
    }

    private void loadSelectedUser() {
        int row = tblUser.getSelectedRow();
        if (row < 0 || row >= displayedUsers.size()) {
            showMessage("Select a user to edit.");
            return;
        }
        selectedUserAccount = displayedUsers.get(row);
        loadUserIntoForm(selectedUserAccount);
    }

    private void loadSelectedOrganization() {
        int row = tblOrganization.getSelectedRow();
        if (row < 0 || row >= displayedOrganizations.size()) {
            showMessage("Select an organization to edit.");
            return;
        }
        selectedOrganization = displayedOrganizations.get(row);
        loadOrganizationIntoForm(selectedOrganization);
    }

    private void loadSelectedEnterprise() {
        int row = tblEnterprise.getSelectedRow();
        if (row < 0 || row >= displayedEnterprises.size()) {
            showMessage("Select an enterprise to edit.");
            return;
        }
        selectedEnterprise = displayedEnterprises.get(row);
        loadEnterpriseIntoForm(selectedEnterprise);
    }

    private void loadUserIntoForm(UserAccount account) {
        if (account == null) {
            return;
        }

        Employee employee = account.getEmployee();
        txtFirstName.setText(employee == null ? "" : employee.getFirstName());
        txtLastName.setText(employee == null ? "" : employee.getLastName());
        txtEmail.setText(employee == null ? "" : employee.getEmail());
        txtPhone.setText(employee == null ? "" : employee.getPhone());
        txtUsername.setText(account.getUsername());
        txtPassword.setText(account.getPassword());

        Organization organization = ecosystem.findOrganizationByUserAccount(account);
        if (organization != null) {
            cmbOragnization.setSelectedItem(organization.getName());
            populateRoleCombo(organization);
        }

        if (account.getRoleType() != null) {
            cmbRole.setSelectedItem(account.getRoleType().getDisplayName());
        }
        cmbEnterprise.setSelectedItem(account.isActive() ? "Active" : "Inactive");
    }

    private void loadOrganizationIntoForm(Organization organization) {
        if (organization == null) {
            return;
        }

        txtName.setText(organization.getName());
        Enterprise enterprise = ecosystem.findEnterpriseByOrganization(organization);
        txtEnterpriseOrg.setText(enterprise == null ? "" : enterprise.getName());
        cmbStatus.setSelectedItem(organization.isActive() ? "Active" : "Inactive");
    }

    private void loadEnterpriseIntoForm(Enterprise enterprise) {
        if (enterprise == null) {
            return;
        }

        txtEnterName.setText(enterprise.getName());
        txtEnterType.setText(enterprise.getType().getDisplayName());
        cmbEnterStatus.setSelectedItem(enterprise.isActive() ? "Active" : "Inactive");
    }

    private void saveUser() {
        String firstName = txtFirstName.getText().trim();
        String lastName = txtLastName.getText().trim();
        String email = txtEmail.getText().trim();
        String phone = txtPhone.getText().trim();
        String username = txtUsername.getText().trim();
        String password = new String(txtPassword.getPassword()).trim();
        Organization organization = findOrganizationByName((String) cmbOragnization.getSelectedItem());
        RoleType roleType = findRoleTypeByDisplayName((String) cmbRole.getSelectedItem());
        boolean active = "Active".equalsIgnoreCase((String) cmbEnterprise.getSelectedItem());

        if (firstName.isEmpty() || username.isEmpty() || password.isEmpty() || organization == null || roleType == null) {
            showMessage("Please complete the user form before saving.");
            return;
        }

        if (selectedUserAccount == null) {
            if (!isUsernameUnique(username, null)) {
                showMessage("Username already exists. Please use a different username.");
                return;
            }

            Employee employee = organization.getEmployeeDirectory().createEmployee(firstName + " " + lastName);
            employee.setFirstName(firstName);
            employee.setLastName(lastName);
            employee.setEmail(email);
            employee.setPhone(phone);

            UserAccount account = organization.getUserAccountDirectory().createUserAccount(username, password, employee, roleType);
            account.setActive(active);
            selectedUserAccount = account;
            showMessage("User created successfully.");
        } else {
            if (!isUsernameUnique(username, selectedUserAccount)) {
                showMessage("Username already exists. Please use a different username.");
                return;
            }

            Organization currentOrganization = ecosystem.findOrganizationByUserAccount(selectedUserAccount);
            if (currentOrganization != null && currentOrganization != organization) {
                currentOrganization.getUserAccountDirectory().removeUserAccount(selectedUserAccount);
                currentOrganization.getEmployeeDirectory().removeEmployee(selectedUserAccount.getEmployee());
                organization.getEmployeeDirectory().addEmployee(selectedUserAccount.getEmployee());
                organization.getUserAccountDirectory().addUserAccount(selectedUserAccount);
            }

            Employee employee = selectedUserAccount.getEmployee();
            employee.setFirstName(firstName);
            employee.setLastName(lastName);
            employee.setEmail(email);
            employee.setPhone(phone);

            selectedUserAccount.setUsername(username);
            selectedUserAccount.setPassword(password);
            selectedUserAccount.setRoleType(roleType);
            selectedUserAccount.setActive(active);
            showMessage("User updated successfully.");
        }

        populateOrganizationCombo();
        populateUserTable(txtSearch.getText());
        clearUserForm();
    }

    private void deleteSelectedUser() {
        if (selectedUserAccount == null) {
            showMessage("Select a user to delete.");
            return;
        }

        Organization organization = ecosystem.findOrganizationByUserAccount(selectedUserAccount);
        if (organization != null) {
            organization.getUserAccountDirectory().removeUserAccount(selectedUserAccount);
            organization.getEmployeeDirectory().removeEmployee(selectedUserAccount.getEmployee());
        }

        showMessage("User deleted successfully.");
        selectedUserAccount = null;
        populateUserTable(txtSearch.getText());
        clearUserForm();
    }

    private void toggleSelectedUserStatus() {
        if (selectedUserAccount == null) {
            showMessage("Select a user to update status.");
            return;
        }

        selectedUserAccount.setActive(!selectedUserAccount.isActive());
        populateUserTable(txtSearch.getText());
        loadUserIntoForm(selectedUserAccount);
        showMessage("User status updated.");
    }

    private void saveOrganization() {
        String organizationName = txtName.getText().trim();
        String enterpriseName = txtEnterpriseOrg.getText().trim();
        Enterprise enterprise = ecosystem.findEnterpriseByName(enterpriseName);
        boolean active = "Active".equalsIgnoreCase((String) cmbStatus.getSelectedItem());

        if (organizationName.isEmpty() || enterprise == null) {
            showMessage("Please enter an organization name and a valid enterprise name.");
            return;
        }

        if (selectedOrganization == null) {
            OrganizationType organizationType = inferOrganizationType(enterprise, organizationName, null);
            Organization organization = enterprise.getOrganizationDirectory().createAndAddOrganization(organizationName, organizationType);
            organization.setActive(active);
            ecosystem.addOrganization(organization);
            selectedOrganization = organization;
            showMessage("Organization created successfully.");
        } else {
            Enterprise currentEnterprise = ecosystem.findEnterpriseByOrganization(selectedOrganization);
            if (currentEnterprise != null && currentEnterprise != enterprise) {
                currentEnterprise.removeOrganization(selectedOrganization);
                enterprise.addOrganization(selectedOrganization);
            }
            selectedOrganization.setName(organizationName);
            selectedOrganization.setActive(active);
            showMessage("Organization updated successfully.");
        }

        populateOrganizationCombo();
        populateOrganizationTable(txtSearchOrg.getText());
        clearOrganizationForm();
    }

    private void deleteSelectedOrganization() {
        if (selectedOrganization == null) {
            showMessage("Select an organization to delete.");
            return;
        }

        Enterprise enterprise = ecosystem.findEnterpriseByOrganization(selectedOrganization);
        if (enterprise != null) {
            enterprise.removeOrganization(selectedOrganization);
        }
        ecosystem.getOrganizationList().remove(selectedOrganization);

        showMessage("Organization deleted successfully.");
        selectedOrganization = null;
        populateOrganizationCombo();
        populateOrganizationTable(txtSearchOrg.getText());
        clearOrganizationForm();
    }

    private void toggleSelectedOrganizationStatus() {
        if (selectedOrganization == null) {
            showMessage("Select an organization to update status.");
            return;
        }

        selectedOrganization.setActive(!selectedOrganization.isActive());
        populateOrganizationTable(txtSearchOrg.getText());
        loadOrganizationIntoForm(selectedOrganization);
        showMessage("Organization status updated.");
    }

    private void saveEnterprise() {
        String name = txtEnterName.getText().trim();
        EnterpriseType type = parseEnterpriseType(txtEnterType.getText().trim());
        boolean active = "Active".equalsIgnoreCase((String) cmbEnterStatus.getSelectedItem());

        if (name.isEmpty() || type == null) {
            showMessage("Please enter a valid enterprise name and enterprise type.");
            return;
        }

        if (selectedEnterprise == null) {
            Enterprise enterprise = createEnterprise(name, type);
            ecosystem.addEnterprise(enterprise);
            enterprise.setActive(active);
            selectedEnterprise = enterprise;
            showMessage("Enterprise created successfully.");
        } else {
            selectedEnterprise.setName(name);
            selectedEnterprise.setType(type);
            selectedEnterprise.setActive(active);
            showMessage("Enterprise updated successfully.");
        }

        populateEnterpriseTable(txtEnterSearch.getText());
        clearEnterpriseForm();
    }

    private void deleteSelectedEnterprise() {
        if (selectedEnterprise == null) {
            showMessage("Select an enterprise to delete.");
            return;
        }

        ecosystem.getEnterpriseList().remove(selectedEnterprise);
        ecosystem.getOrganizationList().removeAll(new ArrayList<>(selectedEnterprise.getOrganization()));

        showMessage("Enterprise deleted successfully.");
        selectedEnterprise = null;
        populateOrganizationCombo();
        populateOrganizationTable(txtSearchOrg.getText());
        populateEnterpriseTable(txtEnterSearch.getText());
        clearEnterpriseForm();
    }

    private void toggleSelectedEnterpriseStatus() {
        if (selectedEnterprise == null) {
            showMessage("Select an enterprise to update status.");
            return;
        }

        selectedEnterprise.setActive(!selectedEnterprise.isActive());
        populateEnterpriseTable(txtEnterSearch.getText());
        loadEnterpriseIntoForm(selectedEnterprise);
        showMessage("Enterprise status updated.");
    }

    private void clearUserForm() {
        txtFirstName.setText("");
        txtLastName.setText("");
        txtEmail.setText("");
        txtPhone.setText("");
        txtUsername.setText("");
        txtPassword.setText("");
        if (cmbOragnization.getItemCount() > 0) {
            cmbOragnization.setSelectedIndex(0);
        }
        populateRoleCombo(findOrganizationByName((String) cmbOragnization.getSelectedItem()));
        if (cmbRole.getItemCount() > 0) {
            cmbRole.setSelectedIndex(0);
        }
        cmbEnterprise.setSelectedItem("Active");
        tblUser.clearSelection();
        selectedUserAccount = null;
    }

    private void clearOrganizationForm() {
        txtName.setText("");
        txtEnterpriseOrg.setText("");
        cmbStatus.setSelectedItem("Active");
        tblOrganization.clearSelection();
        selectedOrganization = null;
    }

    private void clearEnterpriseForm() {
        txtEnterName.setText("");
        txtEnterType.setText("");
        cmbEnterStatus.setSelectedItem("Active");
        tblEnterprise.clearSelection();
        selectedEnterprise = null;
    }

    private Organization findOrganizationByName(String organizationName) {
        if (organizationName == null) {
            return null;
        }

        for (Organization organization : ecosystem.getOrganizationList()) {
            if (organization.getName().equalsIgnoreCase(organizationName)) {
                return organization;
            }
        }
        return null;
    }

    private boolean isUsernameUnique(String username, UserAccount currentAccount) {
        for (UserAccount account : ecosystem.getAllUserAccounts()) {
            if (account != currentAccount && account.getUsername().equalsIgnoreCase(username)) {
                return false;
            }
        }
        return true;
    }

    private RoleType findRoleTypeByDisplayName(String displayName) {
        if (displayName == null) {
            return null;
        }

        for (RoleType roleType : RoleType.values()) {
            if (roleType.getDisplayName().equalsIgnoreCase(displayName)) {
                return roleType;
            }
        }
        return null;
    }

    private EnterpriseType parseEnterpriseType(String value) {
        if (value == null || value.trim().isEmpty()) {
            return null;
        }

        String normalized = normalize(value);
        for (EnterpriseType type : EnterpriseType.values()) {
            if (normalize(type.getDisplayName()).equals(normalized)
                    || normalize(type.name()).equals(normalized)) {
                return type;
            }
        }
        return null;
    }

    private OrganizationType inferOrganizationType(Enterprise enterprise, String organizationName, Organization currentOrganization) {
        if (currentOrganization != null) {
            return currentOrganization.getType();
        }

        String normalized = normalize(organizationName);
        if (normalized.contains("interactive")) {
            return OrganizationType.INTERACTIVE_ENTERTAINMENT;
        }
        if (normalized.contains("game") || normalized.contains("studio")) {
            return OrganizationType.GAME_DEV_STUDIO;
        }
        if (normalized.contains("supplier") || normalized.contains("component")) {
            return OrganizationType.COMPONENT_SUPPLIER;
        }
        if (normalized.contains("manufact")) {
            return OrganizationType.MANUFACTURING_PARTNER;
        }
        if (normalized.contains("retail")) {
            return OrganizationType.RETAILER;
        }
        if (normalized.contains("online") || normalized.contains("service")) {
            return OrganizationType.ONLINE_SERVICE_PROVIDER;
        }

        switch (enterprise.getType()) {
            case DIGITAL_ENTERTAINMENT:
                return OrganizationType.INTERACTIVE_ENTERTAINMENT;
            case HARDWARE_AND_SUPPLY_CHAIN:
                return OrganizationType.COMPONENT_SUPPLIER;
            case PARTNER_AND_SERVICE:
                return OrganizationType.RETAILER;
            default:
                return OrganizationType.INTERACTIVE_ENTERTAINMENT;
        }
    }

    private Enterprise createEnterprise(String name, EnterpriseType type) {
        switch (type) {
            case DIGITAL_ENTERTAINMENT:
                return new DigitalEntertainment(name);
            case HARDWARE_AND_SUPPLY_CHAIN:
                return new HardwareAndSupplyChain(name);
            case PARTNER_AND_SERVICE:
                return new PartnerAndService(name);
            default:
                throw new IllegalArgumentException("Unsupported enterprise type: " + type);
        }
    }

    private String normalize(String value) {
        return value == null ? "" : value.trim().toLowerCase();
    }

    private void showMessage(String message) {
        JOptionPane.showMessageDialog(this, message);
    }
    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateOrgActionPerformed
        // TODO add your handling code here:
        saveOrganization();
    }//GEN-LAST:event_btnUpdateOrgActionPerformed

    private void btnEnterUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterUpdateActionPerformed
        // TODO add your handling code here:
        saveEnterprise();
    }//GEN-LAST:event_btnEnterUpdateActionPerformed

    private void btnAddOrg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOrg1ActionPerformed
        // TODO add your handling code here:
        selectedUserAccount = null;
        clearUserForm();
    }//GEN-LAST:event_btnAddOrg1ActionPerformed

    private void btnAddOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddOrgActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EnterLeftPanel;
    private javax.swing.JPanel EnterRightPanel;
    private javax.swing.JTabbedPane EnterpriseTab;
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JPanel OrgLeftPanel;
    private javax.swing.JPanel OrgRightPanel;
    private javax.swing.JTabbedPane OrgTab;
    private javax.swing.JPanel RightPanel;
    private javax.swing.JTabbedPane UserTab;
    private javax.swing.JButton btnAddOrg;
    private javax.swing.JButton btnAddOrg1;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClearOrg;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteOrg;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnEnterClear;
    private javax.swing.JButton btnEnterDelete;
    private javax.swing.JButton btnEnterSearch;
    private javax.swing.JButton btnEnterUpdate;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearchOrg;
    private javax.swing.JButton btnUpdateOrg;
    private javax.swing.JComboBox<String> cmbEnterStatus;
    private javax.swing.JComboBox<String> cmbEnterprise;
    private javax.swing.JComboBox<String> cmbOragnization;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEnterName;
    private javax.swing.JLabel lblEnterSearch;
    private javax.swing.JLabel lblEnterStatus;
    private javax.swing.JLabel lblEnterType;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblEnterpriseOrg;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblOrgName;
    private javax.swing.JLabel lblOrganization;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblSearchOrg;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTabbedPane mainTab;
    private javax.swing.JTable tblEnterprise;
    private javax.swing.JTable tblOrganization;
    private javax.swing.JTable tblUser;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEnterName;
    private javax.swing.JTextField txtEnterSearch;
    private javax.swing.JTextField txtEnterType;
    private javax.swing.JTextField txtEnterpriseOrg;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSearchOrg;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

}
