/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.WorkAreas;

import Business.WorkSpace.WorkRequestFormData;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.SonyEcoSystem;
import Business.UserAccount.UserAccount;
import UI.MainFrame;
import java.util.function.Consumer;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Hyungs
 */
public class CreateNewWorkRequest extends javax.swing.JPanel {
    
    private final MainFrame mainFrame;
    private final SonyEcoSystem ecosystem;
    private final UserAccount account;
    private final JPanel returnPanel;
    private final Consumer<WorkRequestFormData> submitHandler;
    private final String defaultRequestType;
    private final String requestIdPrefix;


    /**
     * Creates new form CreateNewWorkRequest
     */
    public CreateNewWorkRequest() {
        this(null, null, null, null, null, "", "WR");
    }

    public CreateNewWorkRequest(MainFrame mainFrame,
            SonyEcoSystem ecosystem,
            UserAccount account,
            JPanel returnPanel,
            Consumer<WorkRequestFormData> submitHandler,
            String defaultRequestType,
            String requestIdPrefix) {        
        this.mainFrame = mainFrame;
        this.ecosystem = ecosystem;
        this.account = account;
        this.returnPanel = returnPanel;
        this.submitHandler = submitHandler;
        this.defaultRequestType = defaultRequestType == null ? "" : defaultRequestType;
        this.requestIdPrefix = requestIdPrefix == null || requestIdPrefix.isBlank() ? "WR" : requestIdPrefix;
        initComponents();
        initializeForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblRequestId = new javax.swing.JLabel();
        lblShortDescription = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        lblPriority = new javax.swing.JLabel();
        lblSourceEnterprise = new javax.swing.JLabel();
        lblSourceorg = new javax.swing.JLabel();
        lblTargetEnt = new javax.swing.JLabel();
        lblTargetOrg = new javax.swing.JLabel();
        lblRequestType = new javax.swing.JLabel();
        lblAssignto = new javax.swing.JLabel();
        lblDueDate = new javax.swing.JLabel();
        txtRequestId = new javax.swing.JTextField();
        txtShortDescription = new javax.swing.JTextField();
        txtDescription = new javax.swing.JTextField();
        cmbPriority = new javax.swing.JComboBox<>();
        cmbSourceEnterprise = new javax.swing.JComboBox<>();
        cmbSourceOrg = new javax.swing.JComboBox<>();
        cmbTargetEnt = new javax.swing.JComboBox<>();
        cmbTargetOrg = new javax.swing.JComboBox<>();
        txtRequestType = new javax.swing.JTextField();
        cmbAssignto = new javax.swing.JComboBox<>();
        txtDueDate = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        lblInfo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTitle.setBackground(new java.awt.Color(204, 204, 204));
        lblTitle.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        lblTitle.setText("Create New Work Request Form");

        lblRequestId.setText("Request ID:");

        lblShortDescription.setText("Short Description");

        lblDescription.setText("Description:");

        lblPriority.setText("Priority:");

        lblSourceEnterprise.setText("Source Enterprise:");

        lblSourceorg.setText("Source Organization:");

        lblTargetEnt.setText("Target Enterprise:");

        lblTargetOrg.setText("Target Organization:");

        lblRequestType.setText("Request Type:");

        lblAssignto.setText("Assigned To:");

        lblDueDate.setText("Due Date:");

        cmbPriority.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Low", "Medium", "High" }));

        btnBack.setBackground(new java.awt.Color(204, 204, 204));
        btnBack.setText("<<< Back");
        btnBack.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnSubmit.setBackground(new java.awt.Color(204, 204, 204));
        btnSubmit.setText("Submit");
        btnSubmit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lblInfo.setText("[Low / Medium / High]");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblDueDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblAssignto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblRequestType, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblTargetOrg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblTargetEnt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblSourceEnterprise, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPriority, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblDescription, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblShortDescription, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblRequestId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblSourceorg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtRequestType)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtRequestId, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                                            .addComponent(txtShortDescription)
                                            .addComponent(txtDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cmbPriority, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblInfo))
                                            .addComponent(cmbAssignto, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDueDate)
                                            .addComponent(cmbTargetOrg, 0, 330, Short.MAX_VALUE)
                                            .addComponent(cmbTargetEnt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cmbSourceOrg, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cmbSourceEnterprise, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(192, 192, 192))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(265, 265, 265)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRequestId)
                    .addComponent(txtRequestId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblShortDescription)
                    .addComponent(txtShortDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescription)
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPriority)
                    .addComponent(cmbPriority, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInfo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSourceEnterprise)
                    .addComponent(cmbSourceEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSourceorg)
                    .addComponent(cmbSourceOrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTargetEnt)
                    .addComponent(cmbTargetEnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTargetOrg)
                    .addComponent(cmbTargetOrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRequestType)
                    .addComponent(txtRequestType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAssignto)
                    .addComponent(cmbAssignto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDueDate)
                    .addComponent(txtDueDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSubmit)
                    .addComponent(btnBack))
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        submitForm();
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        navigateBack();
    }//GEN-LAST:event_btnBackActionPerformed

    private void initializeForm() {
        txtRequestType.setText(defaultRequestType);
        txtRequestType.setEditable(false);
        txtRequestId.setText(generateRequestId());
        populateEnterpriseCombos();
        populateAssigneeCombo();
        prefillSourceSelection();
    }

    private void populateEnterpriseCombos() {
        cmbSourceEnterprise.removeAllItems();
        cmbTargetEnt.removeAllItems();
        cmbSourceOrg.removeAllItems();
        cmbTargetOrg.removeAllItems();

        if (ecosystem == null) {
            return;
        }

        for (Enterprise enterprise : ecosystem.getEnterpriseList()) {
            cmbSourceEnterprise.addItem(enterprise.getName());
            cmbTargetEnt.addItem(enterprise.getName());
        }

        cmbSourceEnterprise.addActionListener(evt -> populateOrganizationCombo(cmbSourceEnterprise, cmbSourceOrg));
        cmbTargetEnt.addActionListener(evt -> populateOrganizationCombo(cmbTargetEnt, cmbTargetOrg));

        if (cmbSourceEnterprise.getItemCount() > 0) {
            cmbSourceEnterprise.setSelectedIndex(0);
            populateOrganizationCombo(cmbSourceEnterprise, cmbSourceOrg);
        }
        if (cmbTargetEnt.getItemCount() > 0) {
            cmbTargetEnt.setSelectedIndex(0);
            populateOrganizationCombo(cmbTargetEnt, cmbTargetOrg);
        }
    }

    private void populateOrganizationCombo(javax.swing.JComboBox<String> enterpriseCombo, javax.swing.JComboBox<String> organizationCombo) {
        organizationCombo.removeAllItems();
        if (ecosystem == null) {
            return;
        }

        String enterpriseName = (String) enterpriseCombo.getSelectedItem();
        Enterprise enterprise = ecosystem.findEnterpriseByName(enterpriseName);
        if (enterprise == null) {
            return;
        }

        for (Organization organization : enterprise.getOrganization()) {
            organizationCombo.addItem(organization.getName());
        }
    }

    private void populateAssigneeCombo() {
        cmbAssignto.removeAllItems();
        cmbAssignto.addItem("");
        if (ecosystem == null) {
            return;
        }

        for (UserAccount userAccount : ecosystem.getAllUserAccounts()) {
            cmbAssignto.addItem(userAccount.getUsername());
        }
    }

    private void prefillSourceSelection() {
        if (ecosystem == null || account == null) {
            return;
        }

        Organization organization = ecosystem.findOrganizationByUserAccount(account);
        Enterprise enterprise = ecosystem.findEnterpriseByOrganization(organization);
        if (enterprise != null) {
            cmbSourceEnterprise.setSelectedItem(enterprise.getName());
            populateOrganizationCombo(cmbSourceEnterprise, cmbSourceOrg);
        }
        if (organization != null) {
            cmbSourceOrg.setSelectedItem(organization.getName());
        }
    }

    private String generateRequestId() {
        long suffix = System.currentTimeMillis() % 100000;
        return requestIdPrefix + "-" + String.format("%05d", suffix);
    }

    private void submitForm() {
        if (submitHandler == null) {
            JOptionPane.showMessageDialog(this, "Submit handler is not connected.");
            return;
        }

        String requestId = txtRequestId.getText().trim();
        String shortDescription = txtShortDescription.getText().trim();
        String description = txtDescription.getText().trim();
        String priority = (String) cmbPriority.getSelectedItem();
        String sourceEnterprise = (String) cmbSourceEnterprise.getSelectedItem();
        String sourceOrganization = (String) cmbSourceOrg.getSelectedItem();
        String targetEnterprise = (String) cmbTargetEnt.getSelectedItem();
        String targetOrganization = (String) cmbTargetOrg.getSelectedItem();
        String requestType = txtRequestType.getText().trim();
        String assignedTo = (String) cmbAssignto.getSelectedItem();
        String dueDate = txtDueDate.getText().trim();

        if (shortDescription.isEmpty() || description.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please complete the short description and description.");
            return;
        }

        submitHandler.accept(new WorkRequestFormData(
                requestId,
                shortDescription,
                description,
                priority == null ? "" : priority,
                sourceEnterprise == null ? "" : sourceEnterprise,
                sourceOrganization == null ? "" : sourceOrganization,
                targetEnterprise == null ? "" : targetEnterprise,
                targetOrganization == null ? "" : targetOrganization,
                requestType,
                assignedTo == null ? "" : assignedTo,
                dueDate
        ));
        JOptionPane.showMessageDialog(this, "Work request created successfully.");
        navigateBack();
    }

    private void navigateBack() {
        if (mainFrame != null && returnPanel != null) {
            mainFrame.showRoleDashboard(account, returnPanel);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cmbAssignto;
    private javax.swing.JComboBox<String> cmbPriority;
    private javax.swing.JComboBox<String> cmbSourceEnterprise;
    private javax.swing.JComboBox<String> cmbSourceOrg;
    private javax.swing.JComboBox<String> cmbTargetEnt;
    private javax.swing.JComboBox<String> cmbTargetOrg;
    private javax.swing.JLabel lblAssignto;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblDueDate;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblPriority;
    private javax.swing.JLabel lblRequestId;
    private javax.swing.JLabel lblRequestType;
    private javax.swing.JLabel lblShortDescription;
    private javax.swing.JLabel lblSourceEnterprise;
    private javax.swing.JLabel lblSourceorg;
    private javax.swing.JLabel lblTargetEnt;
    private javax.swing.JLabel lblTargetOrg;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtDueDate;
    private javax.swing.JTextField txtRequestId;
    private javax.swing.JTextField txtRequestType;
    private javax.swing.JTextField txtShortDescription;
    // End of variables declaration//GEN-END:variables
}
