/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.WorkAreas;

import Business.DataGenerator;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.SonyEcoSystem;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import UI.MainFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sumayyahhusain
 */
public class DeveloperWorkAreaJPanel extends javax.swing.JPanel {
    
    private final SonyEcoSystem ecosystem;
    private final UserAccount account;

    /**
     * Creates new form DeveloperWorkAreaJPanel
     */
    
    public DeveloperWorkAreaJPanel() {
        this(DataGenerator.createSeededEcosystem(), null);
    }

    public DeveloperWorkAreaJPanel(SonyEcoSystem ecosystem, UserAccount account) {
        this.ecosystem = ecosystem;
        this.account = account;
        initComponents();
        initializeDeveloperPanel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        WorkRequestTab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        StatusPanel = new javax.swing.JPanel();
        lblCompleted = new javax.swing.JLabel();
        lblActivityProject = new javax.swing.JLabel();
        lblPendingRequest = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRequest = new javax.swing.JTable();
        btnNewRequest = new javax.swing.JButton();
        btnViewDetails = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        MyProfileTab = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnUpdate1 = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblRole = new javax.swing.JLabel();
        txtRole = new javax.swing.JTextField();
        lblOrganization = new javax.swing.JLabel();
        txtOrganization = new javax.swing.JTextField();
        lblEnterprise = new javax.swing.JLabel();
        txtEnterprise = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblPhone = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 204));

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 204));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        WorkRequestTab.setBackground(new java.awt.Color(204, 204, 204));
        WorkRequestTab.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        WorkRequestTab.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        StatusPanel.setBackground(new java.awt.Color(204, 204, 204));
        StatusPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Status", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("맑은 고딕", 1, 12))); // NOI18N

        lblCompleted.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N
        lblCompleted.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCompleted.setText("Completed:");
        lblCompleted.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblActivityProject.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N
        lblActivityProject.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblActivityProject.setText("Active Project: ");
        lblActivityProject.setToolTipText("");
        lblActivityProject.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblPendingRequest.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N
        lblPendingRequest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPendingRequest.setText("Pending Requests:");
        lblPendingRequest.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jScrollPane1.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblRequest.setBackground(new java.awt.Color(204, 204, 204));
        tblRequest.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Request ID", "Title", "To Organization", "Status", "Priority", "Due Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRequest);

        btnNewRequest.setBackground(new java.awt.Color(204, 204, 204));
        btnNewRequest.setText("New Request");
        btnNewRequest.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNewRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewRequestActionPerformed(evt);
            }
        });

        btnViewDetails.setBackground(new java.awt.Color(204, 204, 204));
        btnViewDetails.setText("View Details");
        btnViewDetails.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(204, 204, 204));
        btnUpdate.setText("Update Status");
        btnUpdate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout StatusPanelLayout = new javax.swing.GroupLayout(StatusPanel);
        StatusPanel.setLayout(StatusPanelLayout);
        StatusPanelLayout.setHorizontalGroup(
            StatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(StatusPanelLayout.createSequentialGroup()
                        .addComponent(lblActivityProject, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblPendingRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblCompleted, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addGroup(StatusPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnNewRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnViewDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        StatusPanelLayout.setVerticalGroup(
            StatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatusPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(StatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblActivityProject, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPendingRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCompleted, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(StatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnViewDetails)
                    .addComponent(btnNewRequest))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(StatusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(StatusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        WorkRequestTab.addTab("Enterprise: Digital Entertainment | Org: Game Dev Studio | Role: Game Developer", jPanel1);

        jTabbedPane1.addTab("Work Requests", WorkRequestTab);

        MyProfileTab.setBackground(new java.awt.Color(204, 204, 204));
        MyProfileTab.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        MyProfileTab.setFocusable(false);
        MyProfileTab.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnSave.setBackground(new java.awt.Color(204, 204, 204));
        btnSave.setText("Save");
        btnSave.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnUpdate1.setBackground(new java.awt.Color(204, 204, 204));
        btnUpdate1.setText("Update");
        btnUpdate1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnLogout.setBackground(new java.awt.Color(204, 204, 204));
        btnLogout.setText("Log out");
        btnLogout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblName.setText("Name:");

        lblId.setText("Employee ID");

        lblRole.setText("Role:");

        lblOrganization.setText("Organization:");

        lblEnterprise.setText("Enterprise:");

        lblEmail.setText("Email:");

        lblPhone.setText("Phone:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblRole, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtRole, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblOrganization)
                                    .addComponent(lblEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(247, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRole)
                    .addComponent(txtRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrganization)
                    .addComponent(txtOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEnterprise))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhone)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnUpdate1)
                    .addComponent(btnLogout))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        MyProfileTab.addTab("My Information", jPanel2);

        jTabbedPane1.addTab("My Profile", MyProfileTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
        // TODO add your handling code here:
        showSelectedTableDetails(tblRequest, "Request Details");
    }//GEN-LAST:event_btnViewDetailsActionPerformed

    private void btnNewRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewRequestActionPerformed
        // TODO add your handling code here: "JPanel to CreateNewWorkRequest"
        openCreateRequestForm();

    }//GEN-LAST:event_btnNewRequestActionPerformed

    private void initializeDeveloperPanel() {
        populateMyProfileTab();
        makeProfileReadOnly();
        populateDeveloperRequests();
        btnUpdate.addActionListener(evt -> updateSelectedDeveloperRequest());
        btnUpdate1.addActionListener(evt -> enableProfileEditing());
        btnSave.addActionListener(evt -> saveProfileChanges());
        btnLogout.addActionListener(evt -> logoutToLogin());
    }

    private void populateMyProfileTab() {
        Employee employee = account != null ? account.getEmployee() : null;
        Organization organization = ecosystem != null ? ecosystem.findOrganizationByUserAccount(account) : null;
        Enterprise enterprise = ecosystem != null ? ecosystem.findEnterpriseByOrganization(organization) : null;

        txtName.setText(employee != null ? employee.getName() : "");
        txtRole.setText(account != null && account.getRoleType() != null ? account.getRoleType().getDisplayName() : "");
        txtOrganization.setText(organization != null ? organization.getName() : "");
        txtEnterprise.setText(enterprise != null ? enterprise.getName() : "");
        txtEmail.setText(employee != null ? employee.getEmail() : "");
        txtPhone.setText(employee != null ? employee.getPhone() : "");
        txtId.setText(employee != null ? String.valueOf(employee.getEmployeeId()) : "");

        if (enterprise != null || organization != null || account != null) {
            String enterpriseName = enterprise != null ? enterprise.getName() : "";
            String organizationName = organization != null ? organization.getName() : "";
            String roleName = account != null && account.getRoleType() != null ? account.getRoleType().getDisplayName() : "";
            WorkRequestTab.setTitleAt(0, "Enterprise: " + enterpriseName + " | Org: " + organizationName + " | Role: " + roleName);
        }
    }

    private void makeProfileReadOnly() {
        txtName.setEditable(false);
        txtRole.setEditable(false);
        txtOrganization.setEditable(false);
        txtEnterprise.setEditable(false);
        txtEmail.setEditable(false);
        txtPhone.setEditable(false);
        txtId.setEditable(false);
    }

    private void enableProfileEditing() {
        txtEmail.setEditable(true);
        txtPhone.setEditable(true);
        txtEmail.requestFocus();
    }

    private void saveProfileChanges() {
        Employee employee = account != null ? account.getEmployee() : null;
        if (employee == null) {
            JOptionPane.showMessageDialog(this, "Profile data is not available.");
            return;
        }

        employee.setEmail(txtEmail.getText().trim());
        employee.setPhone(txtPhone.getText().trim());
        populateMyProfileTab();
        makeProfileReadOnly();
        JOptionPane.showMessageDialog(this, "Profile updated successfully.");
    }

    private void logoutToLogin() {
        MainFrame mainFrame = findMainFrame();
        if (mainFrame != null) {
            mainFrame.showLoginScreen();
        }
    }

    private void populateDeveloperRequests() {
        DefaultTableModel model = (DefaultTableModel) tblRequest.getModel();
        model.setRowCount(0);
        model.addRow(new Object[]{"WR-1001", "Gameplay Balancing Notes", "Interactive Entertainment", "Pending", "High", "2026-04-18"});
        model.addRow(new Object[]{"WR-1002", "Publish Patch Summary", "Content Manager", "In Review", "Medium", "2026-04-15"});
        model.addRow(new Object[]{"WR-1003", "Trailer Asset Approval", "Interactive Entertainment", "Completed", "Low", "2026-04-10"});
        lblActivityProject.setText("Active Project: 2");
        lblPendingRequest.setText("Pending Requests: 1");
        lblCompleted.setText("Completed: 1");
    }

    private void updateSelectedDeveloperRequest() {
        int selectedRow = tblRequest.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Select a request first.");
            return;
        }
        tblRequest.setValueAt("Completed", selectedRow, 3);
        lblPendingRequest.setText("Pending Requests: 0");
        lblCompleted.setText("Completed: 2");
    }

    private void openCreateRequestForm() {
        MainFrame mainFrame = findMainFrame();
        if (mainFrame == null) {
            JOptionPane.showMessageDialog(this, "Main screen is not available.");
            return;
        }

        mainFrame.showPanel(new CreateNewWorkRequest(
                mainFrame,
                ecosystem,
                account,
                this,
                this::handleCreatedDeveloperRequest,
                "Developer Request",
                "WR"
        ));
    }

    private void handleCreatedDeveloperRequest(WorkRequestFormData data) {
        DefaultTableModel model = (DefaultTableModel) tblRequest.getModel();
        model.addRow(new Object[]{
            data.getRequestId(),
            data.getShortDescription(),
            data.getTargetOrganization(),
            "Pending",
            data.getPriority(),
            data.getDueDate()
        });

        if (ecosystem != null) {
            Organization senderOrganization = ecosystem.findOrganizationByUserAccount(account);
            Enterprise targetEnterprise = ecosystem.findEnterpriseByName(data.getTargetEnterprise());
            Organization targetOrganization = targetEnterprise != null
                    ? targetEnterprise.findOrganizationByName(data.getTargetOrganization())
                    : null;

            WorkRequest workRequest = new WorkRequest(
                    data.getShortDescription(),
                    senderOrganization,
                    targetOrganization,
                    data.getDescription()
            );
            ecosystem.addWorkRequest(workRequest);
            if (senderOrganization != null) {
                senderOrganization.addWorkRequest(workRequest);
            }
            if (targetOrganization != null && targetOrganization != senderOrganization) {
                targetOrganization.addWorkRequest(workRequest);
            }
        }

        refreshDeveloperStats();
    }

    private void refreshDeveloperStats() {
        int active = tblRequest.getRowCount();
        int pending = 0;
        int completed = 0;
        for (int row = 0; row < tblRequest.getRowCount(); row++) {
            Object statusValue = tblRequest.getValueAt(row, 3);
            String status = statusValue != null ? statusValue.toString() : "";
            if ("Completed".equalsIgnoreCase(status)) {
                completed++;
            } else if ("Pending".equalsIgnoreCase(status) || "In Review".equalsIgnoreCase(status)) {
                pending++;
            }
        }
        lblActivityProject.setText("Active Project: " + active);
        lblPendingRequest.setText("Pending Requests: " + pending);
        lblCompleted.setText("Completed: " + completed);
    }

    private MainFrame findMainFrame() {
        java.awt.Window window = SwingUtilities.getWindowAncestor(this);
        if (window instanceof MainFrame) {
            return (MainFrame) window;
        }
        return null;
    }

    private void showSelectedTableDetails(JTable table, String title) {
        int selectedRow = table.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Select a row first.");
            return;
        }

        StringBuilder builder = new StringBuilder();
        for (int column = 0; column < table.getColumnCount(); column++) {
            builder.append(table.getColumnName(column))
                    .append(": ")
                    .append(table.getValueAt(selectedRow, column))
                    .append("\n");
        }
        JOptionPane.showMessageDialog(this, builder.toString(), title, JOptionPane.INFORMATION_MESSAGE);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane MyProfileTab;
    private javax.swing.JPanel StatusPanel;
    private javax.swing.JTabbedPane WorkRequestTab;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnNewRequest;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdate1;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblActivityProject;
    private javax.swing.JLabel lblCompleted;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOrganization;
    private javax.swing.JLabel lblPendingRequest;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblRole;
    private javax.swing.JTable tblRequest;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEnterprise;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtOrganization;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtRole;
    // End of variables declaration//GEN-END:variables

}
