/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.WorkAreas;

import Business.DataGenerator;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Model.Order;
import Business.Organization.Organization;
import Business.SonyEcoSystem;
import Business.UserAccount.UserAccount;
import UI.MainFrame;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sumayyahhusain
 */
public class ProductionWorkAreaJPanel extends javax.swing.JPanel {

    private final SonyEcoSystem ecosystem;
    private final UserAccount account;

    /**
     * Creates new form ProductionWorkAreaJPanel
     */
    
    public ProductionWorkAreaJPanel() {
        this(DataGenerator.createSeededEcosystem(), null);
    }

    public ProductionWorkAreaJPanel(SonyEcoSystem ecosystem, UserAccount account) {
        this.ecosystem = ecosystem;
        this.account = account;
        initComponents();
        initializeProductionPanel();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        ScheduleTab = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSchedule = new javax.swing.JTable();
        lblActivityProject = new javax.swing.JLabel();
        lblPendingRequest = new javax.swing.JLabel();
        lblCrossEnterprise = new javax.swing.JLabel();
        lblCompleted = new javax.swing.JLabel();
        btnNewOrder = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnRequest = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        ProfileTab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnUpdate1 = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblRole = new javax.swing.JLabel();
        txtRole = new javax.swing.JTextField();
        lblOrganization = new javax.swing.JLabel();
        txtOrganization = new javax.swing.JTextField();
        lblEnterprise = new javax.swing.JLabel();
        txtEnterprise = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblPhone = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 204));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ScheduleTab.setBackground(new java.awt.Color(204, 204, 204));
        ScheduleTab.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ScheduleTab.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jScrollPane1.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblSchedule.setBackground(new java.awt.Color(204, 204, 204));
        tblSchedule.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblSchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Item", "Quantity", "Supplier", "Status", "Start Date", "End Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSchedule);

        lblActivityProject.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N
        lblActivityProject.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblActivityProject.setText("In Production:");
        lblActivityProject.setToolTipText("");
        lblActivityProject.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblPendingRequest.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N
        lblPendingRequest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPendingRequest.setText("Delayed:");
        lblPendingRequest.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblCrossEnterprise.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N
        lblCrossEnterprise.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCrossEnterprise.setText("Cross-Enterprise:");
        lblCrossEnterprise.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblCompleted.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N
        lblCompleted.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCompleted.setText("Completed:");
        lblCompleted.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnNewOrder.setBackground(new java.awt.Color(204, 204, 204));
        btnNewOrder.setText("New Order");
        btnNewOrder.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnUpdate.setBackground(new java.awt.Color(204, 204, 204));
        btnUpdate.setText("Update Progress");
        btnUpdate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnRequest.setBackground(new java.awt.Color(204, 204, 204));
        btnRequest.setText("Request Supplies");
        btnRequest.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnView.setBackground(new java.awt.Color(204, 204, 204));
        btnView.setText("View Details");
        btnView.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblActivityProject, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPendingRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCompleted, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCrossEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 4, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(btnNewOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdate)
                .addGap(18, 18, 18)
                .addComponent(btnRequest)
                .addGap(18, 18, 18)
                .addComponent(btnView)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblActivityProject, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPendingRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCompleted, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCrossEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewOrder)
                    .addComponent(btnUpdate)
                    .addComponent(btnRequest)
                    .addComponent(btnView))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        ScheduleTab.addTab("Enterprise: Hardware and Supply Chain | Org: Manufacturing Partner | Role: Production Manager", jPanel2);

        jTabbedPane1.addTab("Production Schedule", ScheduleTab);

        ProfileTab.setBackground(new java.awt.Color(204, 204, 204));
        ProfileTab.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ProfileTab.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnSave.setBackground(new java.awt.Color(204, 204, 204));
        btnSave.setText("Save");
        btnSave.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnUpdate1.setBackground(new java.awt.Color(204, 204, 204));
        btnUpdate1.setText("Update");
        btnUpdate1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnLogout.setBackground(new java.awt.Color(204, 204, 204));
        btnLogout.setText("Log out");
        btnLogout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblName.setText("Name:");

        lblId.setText("Employee ID");

        lblRole.setText("Role:");

        lblOrganization.setText("Organization:");

        lblEnterprise.setText("Enterprise:");

        lblEmail.setText("Email:");

        lblPhone.setText("Phone:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(243, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblRole, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtRole, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblOrganization)
                            .addComponent(lblEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(262, 262, 262))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRole)
                    .addComponent(txtRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrganization)
                    .addComponent(txtOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEnterprise))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhone)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnUpdate1)
                    .addComponent(btnLogout))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        ProfileTab.addTab("Enterprise: Hardware and Supply Chain | Org: Manufacturing Partner | Role: Production Manager", jPanel1);

        jTabbedPane1.addTab("My Profile", ProfileTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void initializeProductionPanel() {
        populateMyProfileTab();
        makeProfileReadOnly();
        populateSchedule();
        btnView.addActionListener(evt -> showSelectedTableDetails(tblSchedule, "Production Order Details"));
        btnNewOrder.addActionListener(evt -> openCreateRequestForm());
        btnUpdate.addActionListener(evt -> updateSelectedOrderStatus());
        btnRequest.addActionListener(evt -> JOptionPane.showMessageDialog(this, "Supply request action can be connected next."));
    }

    private void populateMyProfileTab() {
        Employee employee = account != null ? account.getEmployee() : null;
        Organization organization = ecosystem != null ? ecosystem.findOrganizationByUserAccount(account) : null;
        Enterprise enterprise = ecosystem != null ? ecosystem.findEnterpriseByOrganization(organization) : null;

        txtName.setText(employee != null ? employee.getName() : "");
        txtRole.setText(account != null && account.getRoleType() != null ? account.getRoleType().getDisplayName() : "");
        txtOrganization.setText(organization != null ? organization.getName() : "");
        txtEnterprise.setText(enterprise != null ? enterprise.getName() : "");
        txtEmail.setText(employee != null ? employee.getEmail() : "");
        txtPhone.setText(employee != null ? employee.getPhone() : "");
        txtId.setText(account != null && account.isActive() ? "Active" : "Inactive");

        if (enterprise != null || organization != null || account != null) {
            String enterpriseName = enterprise != null ? enterprise.getName() : "";
            String organizationName = organization != null ? organization.getName() : "";
            String roleName = account != null && account.getRoleType() != null ? account.getRoleType().getDisplayName() : "";
            ScheduleTab.setTitleAt(0, "Enterprise: " + enterpriseName + " | Org: " + organizationName + " | Role: " + roleName);
            ProfileTab.setTitleAt(0, "My Information");
        }
    }

    private void makeProfileReadOnly() {
        txtName.setEditable(false);
        txtRole.setEditable(false);
        txtOrganization.setEditable(false);
        txtEnterprise.setEditable(false);
        txtEmail.setEditable(false);
        txtPhone.setEditable(false);
        txtStatus.setEditable(false);
    }

    private void populateSchedule() {
        DefaultTableModel model = (DefaultTableModel) tblSchedule.getModel();
        model.setRowCount(0);
        model.addRow(new Object[]{"PO-4581", "PS5 Motherboard", "5000 units", "Foxconn", "In Production", "2026-04-01", "2026-04-20"});
        model.addRow(new Object[]{"PO-4589", "PSVR2 Lens Assembly", "1200 units", "Sony EMS", "Completed", "2026-03-25", "2026-04-12"});
        model.addRow(new Object[]{"PO-4610", "DualSense Chipset", "2500 units", "NXP", "Delayed", "2026-04-05", "2026-04-22"});
        model.addRow(new Object[]{"PO-4625", "PS5 Chassis", "7000 units", "Jabil", "In Production", "2026-04-08", "2026-04-24"});
        lblActivityProject.setText("In Production: 2");
        lblPendingRequest.setText("Delayed: 1");
        lblCompleted.setText("Completed: 1");
        lblCrossEnterprise.setText("Cross-Enterprise: 3");
    }

    private void updateSelectedOrderStatus() {
        int selectedRow = tblSchedule.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Select an order first.");
            return;
        }
        tblSchedule.setValueAt("Completed", selectedRow, 4);
        lblCompleted.setText("Completed: 2");
    }

    private void openCreateRequestForm() {
        MainFrame mainFrame = findMainFrame();
        if (mainFrame == null) {
            JOptionPane.showMessageDialog(this, "Main screen is not available.");
            return;
        }

        mainFrame.showPanel(new CreateNewWorkRequest(
                mainFrame,
                ecosystem,
                account,
                this,
                this::handleCreatedProductionOrder,
                "Production Order",
                "PO"
        ));
    }

    private void handleCreatedProductionOrder(WorkRequestFormData data) {
        DefaultTableModel model = (DefaultTableModel) tblSchedule.getModel();
        model.addRow(new Object[]{
            data.getRequestId(),
            data.getShortDescription(),
            "1 unit",
            data.getSourceOrganization(),
            "Pending",
            LocalDate.now().format(DateTimeFormatter.ISO_DATE),
            data.getDueDate()
        });

        if (ecosystem != null) {
            ecosystem.getProductionOrderList().add(new Order(
                    data.getRequestId(),
                    data.getShortDescription(),
                    1,
                    data.getSourceOrganization(),
                    "Pending",
                    LocalDate.now().format(DateTimeFormatter.ISO_DATE),
                    data.getDueDate()
            ));
        }

        refreshProductionStats();
    }

    private void refreshProductionStats() {
        int inProduction = 0;
        int delayed = 0;
        int completed = 0;
        for (int row = 0; row < tblSchedule.getRowCount(); row++) {
            Object statusValue = tblSchedule.getValueAt(row, 4);
            String status = statusValue != null ? statusValue.toString() : "";
            if ("Completed".equalsIgnoreCase(status)) {
                completed++;
            } else if ("Delayed".equalsIgnoreCase(status)) {
                delayed++;
            } else {
                inProduction++;
            }
        }
        lblActivityProject.setText("In Production: " + inProduction);
        lblPendingRequest.setText("Delayed: " + delayed);
        lblCompleted.setText("Completed: " + completed);
        lblCrossEnterprise.setText("Cross-Enterprise: " + tblSchedule.getRowCount());
    }

    private MainFrame findMainFrame() {
        java.awt.Window window = SwingUtilities.getWindowAncestor(this);
        if (window instanceof MainFrame) {
            return (MainFrame) window;
        }
        return null;
    }

    private void showSelectedTableDetails(JTable table, String title) {
        int selectedRow = table.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Select a row first.");
            return;
        }

        StringBuilder builder = new StringBuilder();
        for (int column = 0; column < table.getColumnCount(); column++) {
            builder.append(table.getColumnName(column))
                    .append(": ")
                    .append(table.getValueAt(selectedRow, column))
                    .append("\n");
        }
        JOptionPane.showMessageDialog(this, builder.toString(), title, JOptionPane.INFORMATION_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane ProfileTab;
    private javax.swing.JTabbedPane ScheduleTab;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnNewOrder;
    private javax.swing.JButton btnRequest;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdate1;
    private javax.swing.JButton btnView;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblActivityProject;
    private javax.swing.JLabel lblCompleted;
    private javax.swing.JLabel lblCrossEnterprise;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOrganization;
    private javax.swing.JLabel lblPendingRequest;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblRole;
    private javax.swing.JTable tblSchedule;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEnterprise;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtOrganization;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtRole;
    // End of variables declaration//GEN-END:variables
}
