/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.WorkAreas;

import Business.DataGenerator;
import Business.Model.Order;
import Business.SonyEcoSystem;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ContentPublishingRequest;
import Business.WorkQueue.WorkRequest;
import Business.WorkQueue.WorkRequestStatus;
import UI.MainFrame;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hyungs
 */
public class WorkRequestManagementJPanel extends javax.swing.JPanel {
    private final SonyEcoSystem ecosystem;
    private final MainFrame mainFrame;
    private final UserAccount account;
    private final javax.swing.JPanel returnPanel;
    private final ArrayList<DashboardEntry> dashboardEntries;
    private boolean dirty;

    /**
     * Creates new form WorkRequestManagementJPanel
     */
    public WorkRequestManagementJPanel(SonyEcoSystem ecosystem) {
        this(null, DataGenerator.createSeededEcosystem(), null, null);
    }
   
    public WorkRequestManagementJPanel(MainFrame mainFrame, SonyEcoSystem ecosystem, UserAccount account, javax.swing.JPanel returnPanel) {
        this.mainFrame = mainFrame;
        this.ecosystem = ecosystem;
        this.account = account;
        this.returnPanel = returnPanel;
        this.dashboardEntries = new ArrayList<>();
        initComponents();
        initializeDashboard();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StatusPanel = new javax.swing.JPanel();
        lblTotalPending = new javax.swing.JLabel();
        lblTotalCross = new javax.swing.JLabel();
        lblTotalComplete = new javax.swing.JLabel();
        lblTotalRequest = new javax.swing.JLabel();
        ApprovalPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDashBoard = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();
        btnRequest1 = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        StatusPanel.setBackground(new java.awt.Color(255, 255, 255));
        StatusPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "All Status", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("맑은 고딕", 1, 12))); // NOI18N
        StatusPanel.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N

        lblTotalPending.setBackground(new java.awt.Color(204, 204, 204));
        lblTotalPending.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalPending.setText("Total Pending:");
        lblTotalPending.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblTotalPending.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTotalCross.setBackground(new java.awt.Color(204, 204, 204));
        lblTotalCross.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalCross.setText("Cross-Enterprise:");
        lblTotalCross.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblTotalCross.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTotalComplete.setBackground(new java.awt.Color(204, 204, 204));
        lblTotalComplete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalComplete.setText("Total Completed:");
        lblTotalComplete.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblTotalComplete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTotalRequest.setBackground(new java.awt.Color(204, 204, 204));
        lblTotalRequest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalRequest.setText("Total Request: ");
        lblTotalRequest.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblTotalRequest.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout StatusPanelLayout = new javax.swing.GroupLayout(StatusPanel);
        StatusPanel.setLayout(StatusPanelLayout);
        StatusPanelLayout.setHorizontalGroup(
            StatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTotalRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(lblTotalPending, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTotalCross, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(lblTotalComplete, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        StatusPanelLayout.setVerticalGroup(
            StatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalPending, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTotalCross, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(lblTotalComplete, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(lblTotalRequest, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                .addContainerGap())
        );

        ApprovalPanel.setBackground(new java.awt.Color(255, 255, 255));
        ApprovalPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Active Work Requests", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("맑은 고딕", 1, 14))); // NOI18N

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblDashBoard.setBackground(new java.awt.Color(204, 204, 204));
        tblDashBoard.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblDashBoard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Request ID", "Title", "Type", "From Org", "To Org", "Status", "Priority"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblDashBoard);

        javax.swing.GroupLayout ApprovalPanelLayout = new javax.swing.GroupLayout(ApprovalPanel);
        ApprovalPanel.setLayout(ApprovalPanelLayout);
        ApprovalPanelLayout.setHorizontalGroup(
            ApprovalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ApprovalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE)
                .addContainerGap())
        );
        ApprovalPanelLayout.setVerticalGroup(
            ApprovalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ApprovalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnBack.setBackground(new java.awt.Color(204, 204, 204));
        btnBack.setText("<<< Back");
        btnBack.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnConfirm.setBackground(new java.awt.Color(204, 204, 204));
        btnConfirm.setText("Delete");
        btnConfirm.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnRequest1.setBackground(new java.awt.Color(204, 204, 204));
        btnRequest1.setText("View Details");
        btnRequest1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblTitle.setBackground(new java.awt.Color(204, 204, 204));
        lblTitle.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Work Request Management - Dashboard");
        lblTitle.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StatusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ApprovalPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(193, 193, 193)
                        .addComponent(btnRequest1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(42, 42, 42)
                .addComponent(StatusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ApprovalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirm)
                    .addComponent(btnBack)
                    .addComponent(btnRequest1))
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        MainFrame frame = mainFrame != null ? mainFrame : findMainFrame();
        if (frame != null && returnPanel != null && account != null) {
            frame.showRoleDashboard(account, returnPanel);
            return;
        }
        if (frame != null) {
            frame.showLoginScreen();
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void initializeDashboard() {
        populateDashboardTable();
        btnRequest1.addActionListener(evt -> showSelectedDetails());
        btnConfirm.addActionListener(evt -> deleteSelectedRequest());
    }

    private void populateDashboardTable() {
        dashboardEntries.clear();
        DefaultTableModel model = (DefaultTableModel) tblDashBoard.getModel();
        model.setRowCount(0);

        if (ecosystem != null) {
            for (WorkRequest workRequest : ecosystem.getWorkRequests()) {
                dashboardEntries.add(createWorkRequestEntry(workRequest));
            }
            for (Order order : ecosystem.getSupplyRequestList()) {
                dashboardEntries.add(createOrderEntry(order, "Supply Request", "Component Supplier", "Manufacturing Partner", "High"));
            }
            for (Order order : ecosystem.getProductionOrderList()) {
                dashboardEntries.add(createOrderEntry(order, "Production Order", order.getFromEnterprise(), "Manufacturing Partner", "Medium"));
            }
            for (Order order : ecosystem.getRestockRequestList()) {
                dashboardEntries.add(createOrderEntry(order, "Retail Request", order.getFromEnterprise(), "Retailer", "Medium"));
            }
        }

        for (DashboardEntry entry : dashboardEntries) {
            model.addRow(new Object[]{
                entry.requestId,
                entry.title,
                entry.type,
                entry.fromOrg,
                entry.toOrg,
                entry.status,
                entry.priority
            });
        }

        updateStatistics();
    }

    private DashboardEntry createWorkRequestEntry(WorkRequest workRequest) {
        String requestId = workRequest instanceof ContentPublishingRequest
                ? ((ContentPublishingRequest) workRequest).getRequestId()
                : "WR-" + Math.abs(workRequest.hashCode());
        String type = workRequest instanceof ContentPublishingRequest ? "Content Publishing" : "Work Request";
        String priority = workRequest instanceof ContentPublishingRequest
                ? ((ContentPublishingRequest) workRequest).getPriority()
                : "Medium";
        String fromOrg = workRequest.getSenderOrganization() != null ? workRequest.getSenderOrganization().getName() : "";
        String toOrg = workRequest.getReceiverOrganization() != null ? workRequest.getReceiverOrganization().getName() : "";
        String message = workRequest.getMessage() != null ? workRequest.getMessage() : "";

        return new DashboardEntry(
                requestId,
                workRequest.getTitle(),
                type,
                fromOrg,
                toOrg,
                formatWorkRequestStatus(workRequest.getStatus()),
                priority,
                message,
                workRequest,
                null
        );
    }

    private DashboardEntry createOrderEntry(Order order, String type, String fromOrg, String toOrg, String priority) {
        return new DashboardEntry(
                order.getOrderId(),
                order.getItemName(),
                type,
                safe(fromOrg),
                safe(toOrg),
                safe(order.getStatus()),
                priority,
                "Order Date: " + safe(order.getOrderDate()) + "\nExpected: " + safe(order.getExpectedDate()),
                null,
                order
        );
    }

    private void updateStatistics() {
        int total = dashboardEntries.size();
        int pending = 0;
        int cross = 0;
        int completed = 0;

        for (DashboardEntry entry : dashboardEntries) {
            String status = entry.status.toLowerCase();
            if (status.contains("pending")
                    || status.contains("new")
                    || status.contains("processing")
                    || status.contains("review")
                    || status.contains("production")
                    || status.contains("delayed")
                    || status.contains("backordered")) {
                pending++;
            }
            if (!entry.fromOrg.isBlank() && !entry.toOrg.isBlank() && !entry.fromOrg.equalsIgnoreCase(entry.toOrg)) {
                cross++;
            }
            if (status.contains("approved")
                    || status.contains("completed")
                    || status.contains("delivered")
                    || status.contains("resolved")
                    || status.contains("closed")
                    || status.contains("shipped")) {
                completed++;
            }
        }

        lblTotalRequest.setText("<html><center>Total Request<br><b>" + total + "</b></center></html>");
        lblTotalPending.setText("<html><center>Total Pending<br><b>" + pending + "</b></center></html>");
        lblTotalCross.setText("<html><center>Cross-Enterprise<br><b>" + cross + "</b></center></html>");
        lblTotalComplete.setText("<html><center>Total Completed<br><b>" + completed + "</b></center></html>");
    }

    private void showSelectedDetails() {
        int selectedRow = tblDashBoard.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Select a work request first.");
            return;
        }

        DashboardEntry entry = dashboardEntries.get(selectedRow);
        String detail = "Request ID: " + entry.requestId
                + "\nTitle: " + entry.title
                + "\nType: " + entry.type
                + "\nFrom Org: " + entry.fromOrg
                + "\nTo Org: " + entry.toOrg
                + "\nStatus: " + entry.status
                + "\nPriority: " + entry.priority
                + "\nMessage: " + entry.message;
        JOptionPane.showMessageDialog(this, detail, "Work Request Details", JOptionPane.INFORMATION_MESSAGE);
    }

    private void editSelectedRequest() {
        int selectedRow = tblDashBoard.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Select a work request first.");
            return;
        }

        DashboardEntry entry = dashboardEntries.get(selectedRow);
        String updatedTitle = JOptionPane.showInputDialog(this, "Edit Title", entry.title);
        if (updatedTitle == null || updatedTitle.trim().isEmpty()) {
            return;
        }

        String updatedPriority = JOptionPane.showInputDialog(this, "Edit Priority", entry.priority);
        if (updatedPriority == null || updatedPriority.trim().isEmpty()) {
            updatedPriority = entry.priority;
        }

        entry.title = updatedTitle.trim();
        entry.priority = updatedPriority.trim();
        applyEntryChanges(entry);
        dirty = true;
        populateDashboardTable();
    }

    private void deleteSelectedRequest() {
        int selectedRow = tblDashBoard.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Select a work request first.");
            return;
        }

        DashboardEntry entry = dashboardEntries.get(selectedRow);
        if (entry.workRequest != null) {
            ecosystem.getWorkRequests().remove(entry.workRequest);
            if (entry.workRequest.getSenderOrganization() != null) {
                entry.workRequest.getSenderOrganization().removeWorkRequest(entry.workRequest);
            }
            if (entry.workRequest.getReceiverOrganization() != null
                    && entry.workRequest.getReceiverOrganization() != entry.workRequest.getSenderOrganization()) {
                entry.workRequest.getReceiverOrganization().removeWorkRequest(entry.workRequest);
            }
        } else if (entry.order != null) {
            ecosystem.getSupplyRequestList().remove(entry.order);
            ecosystem.getProductionOrderList().remove(entry.order);
            ecosystem.getRestockRequestList().remove(entry.order);
        }

        dirty = true;
        populateDashboardTable();
    }

    private void saveDashboardChanges() {
        populateDashboardTable();
        dirty = false;
        JOptionPane.showMessageDialog(this, "Dashboard changes saved.");
    }

    private void applyEntryChanges(DashboardEntry entry) {
        if (entry.workRequest != null) {
            entry.workRequest.setTitle(entry.title);
            if (entry.workRequest instanceof ContentPublishingRequest) {
                ((ContentPublishingRequest) entry.workRequest).setPriority(entry.priority);
            }
        } else if (entry.order != null) {
            entry.order.setItemName(entry.title);
        }
    }

    private String formatWorkRequestStatus(WorkRequestStatus status) {
        if (status == null) {
            return "";
        }
        String raw = status.name().toLowerCase().replace('_', ' ');
        String[] parts = raw.split(" ");
        StringBuilder builder = new StringBuilder();
        for (String part : parts) {
            if (part.isBlank()) {
                continue;
            }
            if (builder.length() > 0) {
                builder.append(' ');
            }
            builder.append(Character.toUpperCase(part.charAt(0))).append(part.substring(1));
        }
        return builder.toString();
    }

    private String safe(String value) {
        return value == null ? "" : value;
    }

    private MainFrame findMainFrame() {
        java.awt.Window window = SwingUtilities.getWindowAncestor(this);
        if (window instanceof MainFrame) {
            return (MainFrame) window;
        }
        return null;
    }

    private static final class DashboardEntry {
        private String requestId;
        private String title;
        private final String type;
        private final String fromOrg;
        private final String toOrg;
        private final String status;
        private String priority;
        private final String message;
        private final WorkRequest workRequest;
        private final Order order;

        private DashboardEntry(
                String requestId,
                String title,
                String type,
                String fromOrg,
                String toOrg,
                String status,
                String priority,
                String message,
                WorkRequest workRequest,
                Order order) {
            this.requestId = requestId;
            this.title = title;
            this.type = type;
            this.fromOrg = fromOrg;
            this.toOrg = toOrg;
            this.status = status;
            this.priority = priority;
            this.message = message;
            this.workRequest = workRequest;
            this.order = order;
        }
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ApprovalPanel;
    private javax.swing.JPanel StatusPanel;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnRequest1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotalComplete;
    private javax.swing.JLabel lblTotalCross;
    private javax.swing.JLabel lblTotalPending;
    private javax.swing.JLabel lblTotalRequest;
    private javax.swing.JTable tblDashBoard;
    // End of variables declaration//GEN-END:variables
}
